version: '3.5'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 15432:5432
    container_name: app.database
    restart: always
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_DATABASE=indtapp
      - POSTGRESQL_USERNAME=indtapp
      - POSTGRESQL_PASSWORD=Postgres2024!
    networks:
      - desafio-indt

  pgadmin:
    image: dpage/pgadmin4
    container_name: app.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=roqls23@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2024!
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - desafio-indt

networks:
  desafio-indt:
    driver: bridge